apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mcp-deployment.fullname" . }}-config
  labels:
    {{- include "mcp-deployment.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "protocol": {
        "version": "{{ .Values.config.protocolVersion }}",
        "transport": "{{ .Values.config.transport }}",
        "timeout": "{{ .Values.config.timeout }}"
      },
      "servers": {
        "sentry": {
          "url": "http://{{ include "mcp-deployment.fullname" . }}-server-sentry:{{ .Values.servers.sentry.port }}"
        },
        "filesystem": {
          "url": "http://{{ include "mcp-deployment.fullname" . }}-server-filesystem:{{ .Values.servers.filesystem.port }}"
        },
        "database": {
          "url": "http://{{ include "mcp-deployment.fullname" . }}-server-database:{{ .Values.servers.database.port }}"
        }
      }
    }
