apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mcp-deployment.fullname" . }}-config
  labels:
    {{- include "mcp-deployment.labels" . | nindent 4 }}
data:
  MCP_HOST: {{ .Values.config.mcpHost | quote }}
  MCP_PORT: {{ .Values.config.mcpPort | quote }}
  UI_TITLE: {{ .Values.config.uiTitle | quote }}
