apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mcp-deployment.fullname" . }}-ui-files
  labels:
    {{- include "mcp-deployment.labels" . | nindent 4 }}
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>{{ .Values.config.uiTitle }}</title>
    </head>
    <body>
      <h1>MCP Dashboard</h1>
      <div id="app"></div>
      <script>
        // Your frontend JavaScript code here
        console.log("MCP UI Loaded");
      </script>
    </body>
    </html>
  style.css: |
    body {
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 20px;
    }
