# Host configuration
host:
  enabled: true
  replicaCount: 1
  image:
    repository: yourregistry/mcp-host
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080

# Client configuration
client:
  enabled: true
  replicaCount: 1
  image:
    repository: yourregistry/mcp-client
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8081
    targetPort: 8081

# UI configuration
ui:
  enabled: true
  replicaCount: 1
  image:
    repository: nginx  # Or your custom UI image
    tag: alpine
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer  # This is critical
    port: 80
    targetPort: 80

# Ingress configuration
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: mcp.yourdomain.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Configuration
config:
  mcpHost: "mcp-host"
  mcpPort: "8080"
  uiTitle: "MCP Dashboard"
