# Host configuration
host:
  enabled: true
  replicaCount: 1
  image:
    repository: nginx  # Temporary public image
    tag: alpine
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080

# Client configuration
client:
  enabled: true
  replicaCount: 1
  image:
    repository: nginx  # Temporary public image
    tag: alpine
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8081
    targetPort: 8081

# UI configuration
ui:
  enabled: true
  replicaCount: 1
  image:
    repository: nginx
    tag: alpine
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    port: 80
    targetPort: 80

# Disabled ingress for now
ingress:
  enabled: false

# Configuration
config:
  mcpHost: "mcp-host"
  mcpPort: "8080"
  uiTitle: "MCP Dashboard"
